
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.1.2"
  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.vm.box_check_update = false
  config.vm.provider "libvirt" do |lb|
    lb.memory = "1024"
    lb.cpus = "2"
   end
  config.vm.provision "shell", path: "provision.sh"
end
