---
- name: Configurar servidor de aplicacao Java
  hosts: app01

  user: vagrant
  become: yes

  vars:
    - dbhost: "db01"
    - dbname: "notes"
    - dbusername: "notesapp"
    - dbpassword: "devopsmaonamassa"

  pre_tasks:
    - name: Upgrade de todos os pacotes do s.o
      yum:
        name: "*"
        state: latest
  roles:
    - configuracao-so

  tasks:
    - name: Adicionar usuario de app
      user:
        name: app
        comment: Usuario de aplicacao
        uid: 500

    - name: Donwload do maven
      get_url:
        url: https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.1.0/apache-maven-3.1.0-bin.tar.gz
        dest: /opt/apache-maven-3.1.0-bin.tar.gz

    - name: Unzip do pacote maven
      ansible.builtin.unarchive:
        src: /opt/apache-maven-3.1.0-bin.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Criando um link simbolico
      file:
        src: "/opt/apache-maven-3.1.0"
        dest: "/opt/maven"
        state: link
        force: yes

    - name: Removendo arquivo tar baixado
      file:
        path: "/opt/apache-maven-3.1.0-bin.tar.gz"
        state: absent

    # - name: Criando um arquivo maven.sh vazio
    #   file:
    #     path: "/etc/profile.d/maven.sh"
    #     state: touch

    - name: Criando um arquivo maven.sh
      become: yes
      copy:
        dest: "/etc/profile.d/maven.sh"
        content: |
          #!/bin/bash
          export JAVA_HOME=/usr/lib/jvm/jre-openjdk
          export M2_HOME=/opt/maven
          export MAVEN_HOME=/opt/maven
          export PATH=${M2_HOME}/bin:${PATH}

    - name: Executando source do arquivo
      shell: source /etc/profile.d/maven.sh

    # - name: Instalacao do Maven
    #   yum:
    #     name: maven
    #     state: latest

    - name: Instalacao do Java
      yum:
        name: java-1.8.0-openjdk
        state: latest

    - name: Criacao do diretorio de app
      file:
        path: /opt/notes
        state: directory
        owner: app
        group: app

    - name: Instalacao do git client
      yum:
        name: git
        state: latest

    - name: Clone do repositorio Notes - app
      git:
        repo: "https://github.com/callicoder/spring-boot-mysql-rest-api-tutorial.git"
        dest: /opt/notes
        clone: yes
        force: yes

    #    - name: Configurar arquivo pom.xml com repositorios maven central
    #      template:
    #        src: pom.xml
    #        dest: /opt/notes/pom.xml

    - name: Copiando arquivo de configuracao pom.xml
      copy:
        src: ./files/pom.xml
        dest: /opt/notes/pom.xml
        owner: app
        group: app
        mode: 0755

    - name: Configurar arquivo de propriedades para camada de banco de dados
      template:
        src: application.properties
        dest: /opt/notes/src/main/resources/application.properties

    - name: Gerar pacote da aplicacao
      become: yes
      shell:
        cmd: /opt/apache-maven-3.1.0/bin/mvn package
        chdir: /opt/notes

    - name: Registrar versao atual do pacote
      become: yes
      shell:
        cmd: /opt/apache-maven-3.1.0/bin/mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version
        chdir: /opt/notes
      register: app_version

    - name: Versao do pacote
      debug:
        msg: Versao "{{ app_version.stdout }}"

    - name: Configurar servico do Systemd
      template:
        src: etc/systemd/system/notes.service
        dest: /etc/systemd/system/notes.service
        owner: root
        group: root
        mode: "0600"
      notify: reload daemon

    - name: Iniciar servico notes
      service:
        name: notes
        state: restarted

  handlers:
    - name: reload app
      systemd:
        state: restarted
        daemon_reload: yes
        name: "notes"

    - name: reload daemon
      systemd:
        daemon_reexec: yes
