---
- name: Configurar servidor de banco de datadog_event
  hosts: db01

  user: vagrant
  become: yes
  vars_files:
    - vars/main.yml
  vars:
    - dbname: "db01"
    - dbusername: "notesapp"
    - dbpasword: "estudo"

  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql
